---
- name: Enable analog audio output port (instead of HDMI)
  shell: "amixer cset numid=3 1"

- include: "packages.yml"
  # shairport seems to work great, but leaving 
  # "shairplay" role intact for future
- include: "shairport.yml"
