---
- name: Clone Shairport repository
  git: repo=https://github.com/abrasive/shairport dest={{shairport_directory}}
  tags: shairport

- name: Build Shairport
  command: chdir={{shairport_directory}} make
  tags:
    - build
    - shairport

- name: Install Shairport
  command: chdir={{shairport_directory}} make install
  tags:
    - build
    - shairport

- name: Create shairport user
  user: name={{shairport_user}} createhome=no system=yes groups=audio append=yes
  tags:
    - shairport
    - system


- name: Daemonize Shairport
  command: cp {{shairport_directory}}/scripts/debian/init.d/shairport /etc/init.d/shairport
  notify: restart shairport
  tags:
    - shairport
    - system

