---
- name: Enable audio output port (instead of HDMI)
  shell: "amixer cset numid=3 1"
  sudo: yes

- name: Install Net::SDP dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - git
    - libao-dev
    - libssl-dev
    - libcrypt-openssl-rsa-perl
    - libio-socket-inet6-perl
    - libwww-perl
    - avahi-utils
    - libmodule-build-perl
  tags: packages

- name: Grab Perl Net:SDP repository
  git: repo=https://github.com/njh/perl-net-sdp.git dest={{perl_sdp_directory}}
  tags: packages git

- name: Build Perl Net:SDP
  command: chdir={{perl_sdp_directory}} perl Build.PL
  sudo: yes
  tags: build

- name: Build Perl Net:SDP test
  command: chdir={{perl_sdp_directory}} ./Build test
  sudo: yes
  tags: build

- name: Build Perl Net:SDP install
  command: chdir={{perl_sdp_directory}} ./Build install
  sudo: yes
  tags: build


- name: Clone Shairport repository
  git: repo=https://github.com/abrasive/shairport dest={{shairport_directory}}
  tags: shairport

- name: Build Shairport
  command: chdir={{shairport_directory}} make
  tags:
    - build
    - shairport

- name: Install Shairport
  command: chdir={{shairport_directory}} make install
  sudo: yes
  tags:
    - build
    - shairport

- name: Clone Shairplay repository.
  git: repo=https://github.com/juhovh/shairplay dest={{shairplay_directory}}
  tags:
    - packages
    - shairplay
    - git

- name: Install Shairplay dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - autoconf
    - automake
    - libtool
    - libltdl-dev
    - libao-dev
    - libavahi-compat-libdnssd-dev
    - avahi-daemon
  tags: 
    - packages
    - shairplay

- name: Generate Shairplay build settings
  command: chdir={{shairplay_directory}} ./autogen.sh
  tags:
    - build
    - shairplay

- name: Configure Shairplay build settings
  command: chdir={{shairplay_directory}} ./configure
  tags:
    - build
    - shairplay

- name: Configure Shairplay build settings
  command: chdir={{shairplay_directory}} make
  tags:
    - build
    - shairplay

- name: Configure Shairplay build settings
  command: chdir={{shairplay_directory}} make install
  sudo: yes
  tags:
    - build
    - shairplay

