---
- name: Enable audio output port (instead of HDMI)
  shell: "amixer cset numid=3 1"
  sudo: yes

- name: Install Shairplay dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - git
    - libao-dev
    - libssl-dev
    - libcrypt-openssl-rsa-perl
    - libio-socket-inet6-perl
    - libwww-perl
    - avahi-utils
    - libmodule-build-perl

- name: Grab Perl Net:SDP repository
  git: repo=https://github.com/njh/perl-net-sdp.git dest={{perl_sdp_directory}}

- name: Build Perl Net:SDP
  command: chdir={{perl_sdp_directory}} perl Build.PL
  sudo: yes
  tags: build

- name: Build Perl Net:SDP test
  command: chdir={{perl_sdp_directory}} ./Build test
  sudo: yes
  tags: build

- name: Build Perl Net:SDP install
  command: chdir={{perl_sdp_directory}} ./Build install
  sudo: yes
  tags: build

- name: Clone Shairplay repository.
  git: repo=https://github.com/hendrikw82/shairport.git dest={{shairplay_directory}}

- name: Make Shairplay
  command: make -c {{shairplay_directory}}



