---
- name: Let's update the apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Now we need to update the Raspbian distribution.
  apt: upgrade=yes

- name: We are setting our new hostname.
  hostname: name={{ hostname }}

- name: Make sure some basic tools are installed
  apt: pkg={{ item }} state=latest
  with_items:
    - unattended-upgrades
    - git
    - curl
    - htop
    - nmap
    - mosh
    - tmux
    - zsh
    - nmon
    - dstat
    - rpi-update
    - haveged
    - avahi-daemon 

- name: Uninstall the massive wolfram-alpha engine
  apt: pkg={{ item }} state=absent
  with_items:
    - wolfram-engine

- name: Autoremove any unused packages.
  shell: "apt-get autoremove --assume-yes --purge"

- name: Let's Autoclean the system.
  shell: "apt-get autoclean --assume-yes"
